import js from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';

/** @type {import('eslint').Linter.Config[]} */
export default [
	js.configs.recommended,
	{
		plugins: { '@stylistic': stylistic },
		rules: {
			'array-callback-return': 'error',
			'constructor-super': 'error',
			'curly': [ 'error', 'all' ],
			'dot-notation': 'error',
			'eqeqeq': 'error',
			'no-alert': 'error',
			'no-bitwise': 'error',
			'no-caller': 'error',
			'no-cond-assign': [ 'error', 'except-parens' ],
			'no-console': 'error',
			'no-const-assign': 'error',
			'no-debugger': 'error',
			'no-dupe-args': 'error',
			'no-dupe-class-members': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-duplicate-imports': 'error',
			'no-else-return': 'error',
			'no-eval': 'error',
			'no-fallthrough': 'error',
			'no-irregular-whitespace': 'error',
			'no-lonely-if': 'error',
			'no-multi-str': 'error',
			'no-nested-ternary': 'error',
			'no-redeclare': 'error',
			'no-shadow': 'error',
			'no-undef-init': 'error',
			'no-undef': 'error',
			'no-unreachable': 'error',
			'no-unsafe-negation': 'error',
			'no-unused-expressions': 'error',
			'no-unused-vars': [ 'error', { ignoreRestSiblings: true } ],
			'no-useless-computed-key': 'error',
			'no-useless-constructor': 'error',
			'no-useless-return': 'error',
			'no-var': 'error',
			'no-with': 'error',
			'object-shorthand': 'error',
			'prefer-const': [ 'error', { destructuring: 'all' } ],
			'valid-typeof': 'error',
			'vars-on-top': 'off',
			'@stylistic/array-bracket-newline': [ 'error', 'consistent' ],
			'@stylistic/array-bracket-spacing': [ 'error', 'always' ],
			'@stylistic/array-element-newline': [ 'error', 'consistent' ],
			'@stylistic/arrow-parens': [ 'error', 'as-needed' ],
			'@stylistic/arrow-spacing': 'error',
			'@stylistic/block-spacing': [ 'error', 'always' ],
			'@stylistic/brace-style': [ 'error', '1tbs' ],
			'@stylistic/comma-dangle': [ 'error', 'always-multiline' ],
			'@stylistic/comma-spacing': 'error',
			'@stylistic/comma-style': [ 'error', 'last' ],
			'@stylistic/computed-property-spacing': [ 'error', 'always' ],
			'@stylistic/dot-location': [ 'error', 'property' ],
			'@stylistic/eol-last': 'error',
			'@stylistic/function-call-argument-newline': [ 'error', 'consistent' ],
			'@stylistic/function-call-spacing': [ 'error', 'never' ],
			'@stylistic/function-paren-newline': [ 'error', 'multiline' ],
			'@stylistic/generator-star-spacing': [ 'error', 'before' ],
			'@stylistic/implicit-arrow-linebreak': [ 'error', 'beside' ],
			'@stylistic/indent': [ 'error', 'tab', { SwitchCase: 1 } ],
			'@stylistic/jsx-quotes': [ 'error', 'prefer-double' ],
			'@stylistic/key-spacing': 'error',
			'@stylistic/keyword-spacing': 'error',
			'@stylistic/line-comment-position': 'error',
			'@stylistic/linebreak-style': [ 'error', 'unix' ],
			'@stylistic/lines-between-class-members': 'error',
			'@stylistic/max-len': [ 'error', {
				code: 120,
				ignoreRegExpLiterals: true,
				ignoreTemplateLiterals: true,
				ignoreUrls: true,
			} ],
			'@stylistic/multiline-ternary': [ 'error', 'always-multiline' ],
			'@stylistic/new-parens': 'error',
			'@stylistic/newline-per-chained-call': [ 'error', { ignoreChainWithDepth: 3 } ],
			'@stylistic/no-confusing-arrow': 'error',
			'@stylistic/no-extra-parens': [ 'error', 'all', {
				allowParensAfterCommentPattern: '@type',
				nestedBinaryExpressions: false,
				returnAssign: false,
				ternaryOperandBinaryExpressions: false,
			} ],
			'@stylistic/no-extra-semi': 'error',
			'@stylistic/no-floating-decimal': 'error',
			'@stylistic/no-mixed-operators': 'error',
			'@stylistic/no-mixed-spaces-and-tabs': 'error',
			'@stylistic/no-multi-spaces': 'error',
			'@stylistic/no-multiple-empty-lines': [ 'error', { max: 1 } ],
			'@stylistic/no-trailing-spaces': 'error',
			'@stylistic/no-whitespace-before-property': 'error',
			'@stylistic/object-curly-spacing': [ 'error', 'always' ],
			'@stylistic/one-var-declaration-per-line': [ 'error', 'initializations' ],
			'@stylistic/operator-linebreak': 'error',
			'@stylistic/padded-blocks': [ 'error', 'never' ],
			'@stylistic/quote-props': [ 'error', 'consistent' ],
			'@stylistic/quotes': [ 'error', 'single', {
				allowTemplateLiterals: 'never',
				avoidEscape: true,
			} ],
			'@stylistic/rest-spread-spacing': 'error',
			'@stylistic/semi-spacing': 'error',
			'@stylistic/semi': [ 'error', 'always' ],
			'@stylistic/space-before-blocks': 'error',
			'@stylistic/space-before-function-paren': [ 'error', {
				anonymous: 'never',
				named: 'never',
				asyncArrow: 'always',
			} ],
			'@stylistic/space-infix-ops': 'error',
			'@stylistic/space-in-parens': [ 'error', 'always' ],
			'@stylistic/space-unary-ops': [ 'error', { overrides: { '!': true, 'yield': true } } ],
			'@stylistic/template-curly-spacing': [ 'error', 'always' ],
			'@stylistic/wrap-iife': 'error',
		},
	},
];
